name: FelNullGDLauncher CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v1.1.*'
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'


      - name: Install Nightly
        run: |
          rustup toolchain install nightly

      - name: Install rust (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          rustup target add x86_64-pc-windows-msvc --toolchain nightly
      - name: Install rust (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin --toolchain nightly
      - name: Install rust (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-gnu --toolchain nightly

      - name: Switch rust to nightly
        run: |
          rustup default nightly

      - name: npm run install
        run: |
          npm i

      - name: npm run lint
        run: |
          npm run lint

      ##Tag Number input
      - name: Get latest release version tag number
        id: get_version
        uses: battila7/get-version-action@v2
      ##ReleaseChannel - go!
      - name: Create Release
        if: matrix.os == 'macos-latest'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: FelNullLauncher - ${{ steps.get_version.outputs.version }}
          body: |
            ダウンロードはこちらから！
            [Windows](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version }}/FelNullGDLauncher-win-setup.exe)
            [Mac OS X](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version }}/FelNullGDLauncher-mac-setup.dmg)
            [Linux](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version }}/FelNullGDLauncher-linux-setup.AppImage)

            Windows : [FelNullGDLauncher-win-setup.exe]を実行すると自動的にインストールが開始し、ソフトが起動します。
            Mac OS X : [FelNullGDLauncher-mac-setup.dmg]を実行してアプリをアプリケーションにコピーしてください。
            Linux : どれでもできればよし！

            ※データフォルダリンク例
            Mac OS X
            /Users/ [user] /Library/Application Support/felnullgdlaucher
            /Users/ [user] /Library/Application Support/felnullgdlaucher_next

            Windows
            C:\Users\ [user] \AppData\Roaming\felnullgdlauncher
            C:\Users\ [user] \AppData\Roaming\felnullgdlauncher_next
            
            Linuxわからん

            Build by ${{ github.actor }}
          draft: false
          prerelease: false



      - name: npm run release for windows
        if: matrix.os == 'windows-latest' && github.event_name == 'push'
        env:
          CI: ''
          TRAVIS_TAG: ''
          APPVEYOR_REPO_TAG_NAME: ''
          CIRCLE_TAG: ''
          BITRISE_GIT_TAG: ''
          GITHUB_ACTIONS: ''
          CI_BUILD_TAG: ''
          RELEASE_TESTING: true
        run: |
          npm run release
      - name: npm run release for mac and linux
        if: matrix.os != 'windows-latest' || github.event_name != 'push'
        env:
          CI: ''
          TRAVIS_TAG: ''
          APPVEYOR_REPO_TAG_NAME: ''
          CIRCLE_TAG: ''
          GITHUB_ACTIONS: ''
          BITRISE_GIT_TAG: ''
          CI_BUILD_TAG: ''
          RELEASE_TESTING: true
        run: |
          npm run release
          
          

      ##ActionRelease - zip
      - uses: actions/upload-artifact@v1
        name: Action-Upload-MacOS
        if: matrix.os == 'macos-latest'
        with:
          name: MacOs Release
          path: deploy
      - uses: actions/upload-artifact@v1
        name: Action-Upload-Windows
        if: matrix.os == 'windows-latest'
        with:
          name: Windows Release
          path: deploy
      - uses: actions/upload-artifact@v1
        name: Action-Upload-Ubuntu
        if: matrix.os == 'ubuntu-latest'
        with:
          name: Linux Release
          path: deploy


      ##GitHub-Release-Upload
      - uses: xresloader/upload-to-github-release@v1
        name: Upload Release File - MacOS
        if: matrix.os != 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          file: "deploy"
          tags: true
          draft: false
          tag_name: ${{ steps.get_version.outputs.version }}
      - uses: xresloader/upload-to-github-release@v1
        name: Upload Release File - Windows
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          file: "deploy"
          tags: true
          draft: false
          overwrite: true
          tag_name: ${{ steps.get_version.outputs.version }}

      - uses: actions/setup-ruby@v1
      - name: Send Webhook Notification
        if: matrix.os == 'macos-latest'
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          git clone https://github.com/gorilla-devs/github-actions-discord-webhook.git webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        shell: bash
